services:
  gamidoc-backend-dev-main:
    image: ghcr.io/yifen9/gamidoc-backend-dev
    env_file:
      - ../.env.dev
    container_name: gamidoc-backend-dev-main
    working_dir: /workspace
    volumes:
      - "..:/workspace"
    command: >
      bash -lc "
        exec sleep infinity
      "
    depends_on:
      - gamidoc-backend-dev-pg
      - gamidoc-backend-dev-redis

  gamidoc-backend-dev-pg:
    image: postgres:18-bookworm
    env_file:
      - ../.env.dev
    container_name: gamidoc-backend-dev-pg
    volumes:
      - gamidoc-backend-dev-pg-data:/var/lib/postgresql

  gamidoc-backend-dev-redis:
    image: redis:8-bookworm
    env_file:
      - ../.env.dev
    container_name: gamidoc-backend-dev-redis
    volumes:
      - gamidoc-backend-dev-redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  gamidoc-backend-dev-pg-data:
  gamidoc-backend-dev-redis-data:
